---
name: Build image check
on:
  pull_request:
    branches: [main]
  push:
    branches: ['*']
  workflow_dispatch:
jobs:
  generate_metadata:
    name: Generate metadata
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install latest-version-cli package
        run: npm install --global latest-version-cli
      - name: Get latest MeshCommander package version and set to variable
        run: echo "::set-output name=npm_mc_version::$(latest-version meshcommander)"
        id: npm
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get current repository tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: tag
      - name: Split tag
        uses: jungwinter/split@v1
        id: semver
        with:
          msg: ${{ steps.tag.outputs.tag }}
          seperator: 'v' #https://github.com/JungWinter/split/issues/4
    outputs:
      current_tag: ${{ steps.semver.outputs._1 }}
      meshcommander_version: ${{ steps.npm.outputs.npm_mc_version }}
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    needs: generate_metadata
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Packer init
        run: packer init .
      - name: Packer validate
        run: packer validate -syntax-only .
      - name: Packer build
        run: |
          packer build -color=false -on-error=abort \
          -var='meshcommander_version=${{ needs.generate_metadata.outputs.meshcommander_version }}' \
          -var='docker_tags=["${{ needs.generate_metadata.outputs.current_tag }}_${{ needs.generate_metadata.outputs.meshcommander_version }}","latest"]' \
          .