---
name: build_and_push_image
on:
  create:
    tags: ['v*']
  pull_request:
    branches: [$default-branch]
  push:
    branches: [$default-branch]
    tags: ['v*']
  repository_dispatch:
    types: [build]
  workflow_dispatch:
jobs:
  generate_metadata:
    name: Generate metadata
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      # - run: npm install --global latest-version-cli
      # - run: echo "::set-output name=mc_version::$(latest-version meshcommander)"
      #   id: version
      - name: Generate Docker tags
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ github.repository }}
          tags: |
            type=sha,prefix=
            type=semver,pattern={{version}}
          flavor: |
            latest=auto
            suffix=_${{ github.event.client_payload.meshcommander_version }}
    outputs:
      # meshcommander_version: ${{ steps.version.outputs.mc_version }}
      docker_metadata: ${{ steps.meta.outputs.version }}
  build_push_container:
    name: Build and push container
    runs-on: ubuntu-latest
    needs: generate_metadata
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Packer init
        run: packer init .
      - name: Packer validate
        run: packer validate -syntax-only .
      - name: Packer build
        run: |
          packer build -color=false -on-error=abort \
          -var meshcommander_version=${{ github.event.client_payload.meshcommander_version }} \
          -var docker_tags=${{ needs.generate_metadata.outputs.docker_metadata }} \
          .
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker image push --all-tags ${{ github.repository }}
      - name: Push description to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}