---
name: Repository Dispatch
on:
  workflow_dispatch:
  schedule:
    - cron: '35 7 * * *'
jobs:
  check_meshcommander_version:
    name: Check MeshCommander version
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install latest-version-cli package
        run: npm install --global latest-version-cli
      - name: Get latest MeshCommander package version and set to variable
        run: echo "::set-output name=mc_version::$(latest-version meshcommander)"
        id: version
      - name: Trigger build_and_deploy workflow if MeshCommander version updated
        uses: peter-evans/repository-dispatch@v1
        if: ${{ steps.version.outputs.mc_version != '0.9.0-c' }}
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: build
          client-payload: '{"meshcommander_version": "${{ steps.version.outputs.mc_version }}"}'
