---
name: deploy_new_container
on:
  workflow_dispatch:
  create:
    tags:
       - 'v*'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
jobs:
  generate_metadata:
    name: Generate metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --global latest-version-cli
      - run: echo "::set-output name=mc_version::$(latest-version meshcommander)"
        id: version
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: bendwyer/docker-meshcommander
          tags: |
            type=sha,prefix=
            type=semver,pattern={{version}}
          flavor: |
            latest=auto
            suffix=_${{ steps.version.outputs.mc_version }}
    outputs:
      meshcommander_version: ${{ steps.version.outputs.mc_version }}
      docker_metadata: ${{ steps.meta.outputs.tags }}
  build_container:
    name: Build container
    runs-on: ubuntu-latest
    needs: generate_metadata
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Packer init
        run: packer init .
      - name: Packer validate
        run: packer validate -syntax-only .
      - name: Packer build
        run: packer build -color=false -on-error=abort \
          -var meshcommander_version=${{ needs.generate_metadata.outputs.meshcommander_version }} \
          -var docker_tags=${{ needs.generate_metadata.outputs.docker_metadata }} \
          .