---
name: deploy_new_container
on: workflow_dispatch
jobs:
  get_meshcommander_version:
    name: Get MeshCommander version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --global latest-version-cli
      - run: echo "::set-output name=version::$(latest-version meshcommander)"
        id: get_version
    outputs:
      meshcommander_version: ${{ steps.get_version.outputs.version }}
  build_container:
    name: Build container
    runs-on: ubuntu-latest
    needs: get_meshcommander_version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Packer init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: .
      - name: Packer validate
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: .
      - name: Packer build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var meshcommander_version=${{ needs.get_meshcommander_version.outputs.meshcommander_version }}"
          target: .
        env:
          PACKER_LOG: 1