---
name: Update Docker image version
on:
  pull_request:
    branches: [$default-branch]
  push:
    branches: [$default-branch]
    tags: ['v*']
  workflow_dispatch:
jobs:
  get_meshcommander_version:
    name: Get MeshCommander version
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install latest-version-cli package
        run: npm install --global latest-version-cli
      - name: Get latest MeshCommander package version and set to variable
        run: echo "::set-output name=npm_mc_version::$(latest-version meshcommander)"
        id: npm
      - name: Trigger build_and_push_image action
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: bump_docker_image_version
          client-payload: '{"meshcommander_version": "${{ steps.npm.outputs.npm_mc_version }}","action_trigger": "${{ github.event_name }}"}'